# 参考記事 https://zenn.dev/tmasuyama1114/books/ab51fea5d5f659/viewer/rubocop

require: rubocop-rails

AllCops:
  # 除外するディレクトリ（自動生成されるファイル）
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "Gemfile"

  # 新ルールを有効化
  NewCops: enable
  # rubocop-capybaraの提案を非表示にする
  SuggestExtensions: false

# 1行あたりの文字数をチェックする
Layout/LineLength:
  Max: 100
  # 下記ファイルはチェックの対象から外す
  Exclude:
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "app/models/user.rb"
    - "app/uploaders/avatar_uploader.rb"
    - "app/helpers/application_helper.rb"
    - "app/controllers/users_controller.rb"

# RSpecは1つのブロックあたりの行数が多くなるため、チェックの除外から外す
# ブロック内の行数をチェックする
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
Metrics/AbcSize:
  Max: 10
  Exclude:
    - "app/controllers/quizzes_controller.rb"
    - "app/controllers/users_controller.rb"

# メソッドの中身が複雑になっていないか、Rubocopが計算して基準値を超えると警告を出す
Metrics/PerceivedComplexity:
  Max: 8

# 循環的複雑度が高すぎないかをチェック（ifやforなどを1メソッド内で使いすぎている）
Metrics/CyclomaticComplexity:
  Max: 10

# メソッドの行数が多すぎないかをチェック
Metrics/MethodLength:
  Max: 10
  Exclude:
    - "app/helpers/application_helper.rb"
    - "app/controllers/quizzes_controller.rb"

# ネストが深すぎないかをチェック（if文のネストもチェック）
Metrics/BlockNesting:
  Max: 5

# クラスの行数をチェック（無効）
Metrics/ClassLength:
  Enabled: false

# 空メソッドの場合に、1行のスタイルにしない　NG例：def style1; end
Style/EmptyMethod:
  EnforcedStyle: expanded

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
  Enabled: false

# ％i（）構文を使用していないシンボルで構成される配列リテラルをチェック（無効）
Style/SymbolArray:
  Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
  Enabled: false

# 文字列補間や特殊記号（"）を必要としない場合は、単一引用符で囲まれた文字列を使用することを推奨（無効）
Style/StringLiterals:
  EnforcedStyle: double_quotes

# メソッドパラメータ名の最小文字数を設定
Naming/MethodParameterName:
  MinNameLength: 1

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "app/controllers/users/registrations_controller.rb"

Lint/UnusedMethodArgument:
  Exclude:
    - "app/uploaders/avatar_uploader.rb"

Rails/FilePath:
  Exclude:
    - "spec/rails_helper.rb"

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"
